# Generated by Django 2.2.3 on 2019-07-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.TextField(default='mu', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.TextField(default='um', max_length=20),
        ),
    ]
