# Generated by Django 2.2.3 on 2019-07-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190705_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default='123', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='uniqname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
